Title: 313847 – python-3.1.2-r1 changelog lists invalid bug number
URL: https://bugs.gentoo.org/show_bug.cgi?id=313847

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 313847
python-3.1.2-r1 changelog lists invalid bug number
Last modified: 2010-04-08 16:00:52 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 313847 
      - python-3.1.2-r1 changelog lists invalid bug number


Summary:
python-3.1.2-r1 changelog lists invalid bug number
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

New packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
High
       trivial
      


Assignee:

Gentoo Linux bug wranglers








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2010-04-08 11:28 UTC by Richard Hartmann





      Modified:
    
2010-04-08 16:00 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Richard Hartmann





          2010-04-08 11:28:45 UTC
        

The below mentioned bug number 1583863 does not exist.

*python-3.1.2-r1 (25 Mar 2010)

  25 Mar 2010; Arfrever Frehtes Taifersar Arahesis (arfrever)
  +python-3.1.2-r1.ebuild:
  Allow str subclasses to override __str__ method (Python issue #1583863).


Reproducible: Always




Comment 1


Arfrever Frehtes Taifersar Arahesis (RETIRED)






          2010-04-08 15:43:18 UTC
        

It's a Python upstream issue.
http://bugs.python.org/issue1583863




Comment 2


Richard Hartmann





          2010-04-08 16:00:52 UTC
        


Oh sorry for wasting your time. Than it is a bug on znurt.org, I have reported it to its maintainer.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

