Title: 92275 – emerge dev-python/pyopengl dies with "multiple definition of `glSampleCoverageARB'"
URL: https://bugs.gentoo.org/show_bug.cgi?id=92275

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 92275
emerge dev-python/pyopengl dies with "multiple definition of `glSampleCoverageARB'"
Last modified: 2005-05-24 16:28:56 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 92275 
      - emerge dev-python/pyopengl dies with "multiple definition of `glSampleCoverageARB'"


Summary:
emerge dev-python/pyopengl dies with "multiple definition of `glSampleCoverag...
        









Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

[OLD] Unspecified

  (show other bugs)



Hardware:

x86
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Python Gentoo Team








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2005-05-11 11:02 UTC by Josh Scheid





      Modified:
    
2005-05-24 16:28 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Josh Scheid





          2005-05-11 11:02:11 UTC
        

This looks like a different failure than Bug 85261.

i686-pc-linux-gnu-gcc -pthread -shared -march=pentium4 -O3 -pipe -fomit-frame-pointer build/temp.linux-i686-2.3/src/interface/GL.ARB.multisample.o -L/usr/lib -L/usr/local/lib -L/usr/X11R6/lib -Lbuild/temp.linux-i686-2.3 -lGL -lX11 -lXext -lGLU -linterface_util -lGLE -o build/lib.linux-i686-2.3/OpenGL/GL/ARB/multisample.so
/usr/lib/libGL.a(glapi_x86.o)(.text+0x3380): In function `glSampleCoverageARB':
: multiple definition of `glSampleCoverageARB'
build/temp.linux-i686-2.3/src/interface/GL.ARB.multisample.o(.text+0x1d6): first defined here
collect2: ld returned 1 exit status
error: command 'i686-pc-linux-gnu-gcc' failed with exit status 1


Reproducible: Always
Steps to Reproduce:
1. emerge dev-python/pyopengl

Actual Results:  
Build fails.

Expected Results:  
Build succeeds.

I did "opengl-update xorg-x11; env-update; source /etc/profile" just to be sure
and this problem still occurs.

Portage 2.0.51.19 (default-linux/x86/2005.0, gcc-3.3.5-20050130,
glibc-2.3.4.20041102-r1, 2.6.11-gentoo-r6 i686)
=================================================================
System uname: 2.6.11-gentoo-r6 i686 Intel(R) Pentium(R) 4 CPU 2.40GHz
Gentoo Base System version 1.4.16
Python:              dev-lang/python-2.3.5 [2.3.5 (#1, May  9 2005, 20:51:42)]
dev-lang/python:     2.3.5
sys-apps/sandbox:    [Not Present]
sys-devel/autoconf:  2.13, 2.59-r6
sys-devel/automake:  1.5, 1.8.5-r3, 1.6.3, 1.7.9-r1, 1.4_p6, 1.9.5
sys-devel/binutils:  2.15.92.0.2-r7
sys-devel/libtool:   1.5.16
virtual/os-headers:  2.6.8.1-r2
ACCEPT_KEYWORDS="x86"
AUTOCLEAN="yes"
CFLAGS="-march=pentium4 -O3 -pipe -fomit-frame-pointer"
CHOST="i686-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/kde/2/share/config /usr/kde/3.3/env
/usr/kde/3.3/share/config /usr/kde/3.3/shutdown /usr/kde/3/share/config
/usr/lib/X11/xkb /usr/share/config /var/qmail/control"
CONFIG_PROTECT_MASK="/etc/gconf /etc/terminfo /etc/env.d"
CXXFLAGS="-march=pentium4 -O3 -pipe -fomit-frame-pointer"
DISTDIR="/usr/portage/distfiles"
FEATURES="autoaddcvs autoconfig ccache distlocks fixpackages sandbox sfperms strict"
GENTOO_MIRRORS="ftp://mirror.iawnet.sandia.gov/pub/gentoo/
ftp://gentoo.mirrors.pair.com/ ftp://csociety-ftp.ecn.purdue.edu/pub/gentoo/"
LC_ALL="POSIX"
MAKEOPTS="-j2"
PKGDIR="/usr/portage/packages"
PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/usr/portage"
SYNC="rsync://rsync.us.gentoo.org/gentoo-portage"
USE="x86 X Xaw3d aalib alsa apm arts avi berkdb bitmap-fonts cdparanoia cdr
crypt cscope cups curl divx4linux emboss encode esd fam flac foomaticdb fortran
gdbm gif gimpprint gnome gpm gtk gtk2 imagemagick imlib ipv6 java jpeg ldap
libg++ libwww mad mikmod mmx mmxext motif mozilla mp3 mpeg ncurses nls ogg
oggvorbis opengl oss pam pdflib perl png python quicktime readline real sdl
spell sse sse2 ssl svg svga tcltk tcpd theora threads tiff truetype
truetype-fonts type1-fonts vorbis xinerama xml2 xmms xprint xv xvid zlib
userland_GNU kernel_linux elibc_glibc"
Unset:  ASFLAGS, CBUILD, CTARGET, LANG, LDFLAGS, LINGUAS, PORTDIR_OVERLAY




Comment 1


Fernando Serboncini (RETIRED)






          2005-05-22 09:43:32 UTC
        

can you tell me which version of pyopengl did you try to emerge?




Comment 2


Josh Scheid





          2005-05-23 10:52:53 UTC
        

Heh, go figure.  I've been doing other things with the box, one of which was to
rebuild xorg to try and resolve Bug 92306.  After that, this morning I emerged
pyopengl-2.0.0.44 successfully.  Something must have been messed up with opengl
in my previous (same version) build of xorg.

This bug is resolved, but I don't know how you wish to mark Resolution.




Comment 3


Alastair Tse (RETIRED)






          2005-05-24 16:28:56 UTC
        

marking it worksforme for now. there are quite a few of this transient pyopengl bugs, it seems.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

