Title: 327249 – python-updater creates invalid merge list
URL: https://bugs.gentoo.org/show_bug.cgi?id=327249

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 327249
python-updater creates invalid merge list
Last modified: 2010-07-07 15:21:45 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 327249 
      - python-updater creates invalid merge list


Summary:
python-updater creates invalid merge list
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Gentoo Linux bug wranglers








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2010-07-07 04:44 UTC by David





      Modified:
    
2010-07-07 15:21 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


David





          2010-07-07 04:44:38 UTC
        

When running python-updater, it tries to emerge this:  app-office/-MERGING-openoffice-bin:0


The package name '-MERGING-openoffice-bin' is invalid, and so the process dies with this message:

!!! 'app-office/-MERGING-openoffice-bin:0' is not a valid package atom.

Reproducible: Always

Steps to Reproduce:

Actual Results:  
# python-updater
 * Starting Python Updater...
 * Main active version of Python:  2.6
 * Active version of Python 2:     2.6
 * Active version of Python 3:     3.1
 *   Adding to list: app-office/-MERGING-openoffice-bin:0
 *   Adding to list: app-office/openoffice-bin:0
 *   Adding to list: dev-java/java-config:2
 *   Adding to list: dev-libs/boost:1.41
 *     check: manual [Added to list manually, see CHECKS in manpage for more information.]
 *   Adding to list: x11-libs/vte:0
 *     check: manual [Added to list manually, see CHECKS in manpage for more information.]
 * emerge -Dv1 --keep-going app-office/-MERGING-openoffice-bin:0 app-office/openoffice-bin:0 dev-java/java-config:2 dev-libs/boost:1.41 x11-libs/vte:0
!!! 'app-office/-MERGING-openoffice-bin:0' is not a valid package atom.
!!! Please check ebuild(5) for full details.


Expected Results:  
I expected it to emerge 'openoffice-bin' without the false '-MERGING-openoffice-bin'




Comment 1


Arfrever Frehtes Taifersar Arahesis (RETIRED)






          2010-07-07 04:54:22 UTC
        

Your VDB (/var/db/pkg) contains -MERGING-* directory. It was caused by interruption of merging of files of that package from "${D}" to "${ROOT}".




Comment 2


David





          2010-07-07 05:39:59 UTC
        

(In reply to comment #1)
> Your VDB (/var/db/pkg) contains -MERGING-* directory. It was caused by
> interruption of merging of files of that package from "${D}" to "${ROOT}".


Thank you.

I do find that I have a '/var/db/pkg/app-office/-MERGING-openoffice-bin-3.1.1/' directory (even though I have openoffice-bin-3.2.0 installed).

The average user probably won't know the cause (or solution) for this issue.

       So, I believe that python-updater should catch the fact that '-MERGING-openoffice-bin' is an invalid package atom, and not try to emerge it.

       Or, it seems that some process (eclean, or portage itself) could have removed the unneeded '-MERGING-openoffice-bin-3.1.1' directory.


I will venture to reopen the bug, hoping that a user-friendly option could be created to (perhaps automatically) deal with this issue, so that it doesn't catch other Gentoo users off guard.




Comment 3


Arfrever Frehtes Taifersar Arahesis (RETIRED)






          2010-07-07 15:21:45 UTC
        

It would be a duplicate of bug #192778 and bug #217345.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

