Title: 674000 – dev-python/odfpy-1.3.6 :  * (no error message)
URL: https://bugs.gentoo.org/show_bug.cgi?id=674000

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 674000
dev-python/odfpy-1.3.6 :  * (no error message)
Last modified: 2018-12-31 08:15:43 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 674000 
      - dev-python/odfpy-1.3.6 :  * (no error message)


Summary:
dev-python/odfpy-1.3.6 :  * (no error message)
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
Normal
       normal
      


Assignee:

Python Gentoo Team








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2018-12-29 15:57 UTC by Toralf Förster





      Modified:
    
2018-12-31 08:15 UTC
      (History)
    




          CC List:
        

1 
          user
          
            (show)
          



vdupras









See Also:






Package list:







Runtime testing required:

---























      Attachments
    




emerge-info.txt

              (emerge-info.txt,14.60 KB,
                text/plain)

            
2018-12-29 15:57 UTC,

            Toralf Förster




Details





dev-python:odfpy-1.3.6:20181229-155552.log

              (dev-python:odfpy-1.3.6:20181229-155552.log,28.81 KB,
                text/plain)

            
2018-12-29 15:57 UTC,

            Toralf Förster




Details





emerge-history.txt

              (emerge-history.txt,41.78 KB,
                text/plain)

            
2018-12-29 15:57 UTC,

            Toralf Förster




Details





environment

              (environment,107.96 KB,
                text/plain)

            
2018-12-29 15:57 UTC,

            Toralf Förster




Details





etc.portage.tbz2

              (etc.portage.tbz2,11.87 KB,
                application/x-bzip)

            
2018-12-29 15:57 UTC,

            Toralf Förster




Details





temp.tbz2

              (temp.tbz2,25.83 KB,
                application/x-bzip)

            
2018-12-29 15:57 UTC,

            Toralf Förster




Details





View All

Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Toralf Förster






          2018-12-29 15:57:32 UTC
        

 * ERROR: dev-python/odfpy-1.3.6::gentoo failed (install phase):
 *   (no error message)
 * 

  -------------------------------------------------------------------

  This is an unstable amd64 chroot image at a tinderbox (==build bot)
  name: 17.0-systemd_test_20181228-124659

  -------------------------------------------------------------------

gcc-config -l:
 [1] x86_64-pc-linux-gnu-8.2.0 *

Available Python interpreters, in order of preference:
  [1]   python3.6
  [2]   python2.7 (fallback)





emerge -qpvO dev-python/odfpy
[ebuild  N    ] dev-python/odfpy-1.3.6  USE="-examples -test" PYTHON_TARGETS="python2_7 python3_6 -python3_4 -python3_5 -python3_7"




Comment 1


Toralf Förster






          2018-12-29 15:57:35 UTC
        

Created attachment 558844 [details]
emerge-info.txt




Comment 2


Toralf Förster






          2018-12-29 15:57:38 UTC
        

Created attachment 558846 [details]
dev-python:odfpy-1.3.6:20181229-155552.log




Comment 3


Toralf Förster






          2018-12-29 15:57:40 UTC
        

Created attachment 558848 [details]
emerge-history.txt




Comment 4


Toralf Förster






          2018-12-29 15:57:43 UTC
        

Created attachment 558850 [details]
environment




Comment 5


Toralf Förster






          2018-12-29 15:57:46 UTC
        

Created attachment 558852 [details]
etc.portage.tbz2




Comment 6


Toralf Förster






          2018-12-29 15:57:48 UTC
        

Created attachment 558854 [details]
temp.tbz2




Comment 7


Virgil Dupras (RETIRED)






          2018-12-29 21:23:17 UTC
        

I'm having troubles reproducing the problem. I've tried installing on stable/unstable amd64 systems, with tests enabled/disabled and couldn't trigger the error.

That being said, all these tests were with openrc (I see that the tinderbox is on systemd).

Can someone else reproduce?




Comment 8


Toralf Förster






          2018-12-30 13:27:35 UTC
        

Even on this image it proceeds now:

/home/tinderbox/run/17.0-systemd_test_20181228-124659/var/log/emerge.log
Sat Dec 29 22:39:25 2018 >>> dev-python/odfpy-1.3.6
odfpy: Sat Dec 29 22:39:08 2018: 17 seconds
odfpy: 1 times


Hhm?




Comment 9


Virgil Dupras (RETIRED)






          2018-12-31 03:03:02 UTC
        

If the problem can't be reproduced, maybe we should close the bug?









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

