Title: 575624 – unoconv Python requirements clash with Libre Office
URL: https://bugs.gentoo.org/show_bug.cgi?id=575624

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 575624
unoconv Python requirements clash with Libre Office
Last modified: 2016-05-05 00:17:34 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 575624 
      - unoconv Python requirements clash with Libre Office


Summary:
unoconv Python requirements clash with Libre Office
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
Normal
       normal
      


Assignee:

Gentoo Linux bug wranglers








URL:







Whiteboard:




Keywords:









Duplicates (1):
    

575758

      (view as bug list)
    


Depends on:







Blocks:









 





      Reported:
    
2016-02-25 11:05 UTC by PetaMem R&D





      Modified:
    
2016-05-05 00:17 UTC
      (History)
    




          CC List:
        

4 
          users
          
            (show)
          



bkohler
hlein
tdalman
yellowhat46









See Also:






Package list:







Runtime testing required:

---























      Attachments
    




Update unoconv ebuild to target python 3_4 for ooo compatability

              (unoconv-python3_4.patch,250 bytes,
                patch)

            
2016-05-05 00:17 UTC,

            Hank Leininger




Details
            | Diff





View All

Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


PetaMem R&D





          2016-02-25 11:05:00 UTC
        

!!! The ebuild selected to satisfy "app-office/libreoffice" has unmet requirements.
app-office/libreoffice-5.1.0.3::gentoo
...
  The following REQUIRED_USE flag constraints are unsatisfied:
    exactly-one-of ( python_single_target_python3_4 python_single_target_python3_5 )

vs.

!!! The ebuild selected to satisfy "app-office/unoconv" has unmet requirements.
- app-office/unoconv-0.7::gentoo USE="" PYTHON_SINGLE_TARGET="-python2_7 -python3_3" PYTHON_TARGETS="python2_7 -python3_3"

  The following REQUIRED_USE flag constraints are unsatisfied:
    exactly-one-of ( python_single_target_python2_7 python_single_target_python3_3 )


PYTHON_SINGLE_TARGET cannot be satisfied




Comment 1


Ben Kohler






          2016-02-25 15:52:14 UTC
        

You can set PYTHON_SINGLE_TARGET to a new value for libreoffice only, with a package.use entry like:

app-office/libreoffice python_single_targets_python3_4

or with recent portage versions:

app-office/libreoffice PYTHON_SINGLE_TARGETS: python3_4




Comment 2


PetaMem R&D





          2016-02-25 17:28:20 UTC
        

ok.

except you meant 

app-office/libreoffice python_single_target_python3_4

or with recent portage versions:

app-office/libreoffice PYTHON_SINGLE_TARGET: python3_4


(observe the missing plural in "target")

seems to workforme too.




Comment 3


Ben Kohler






          2016-02-26 19:29:09 UTC
        

*** Bug 575758 has been marked as a duplicate of this bug. ***




Comment 4


Hank Leininger





          2016-05-05 00:16:17 UTC
        

> You can set PYTHON_SINGLE_TARGET to a new value for libreoffice only, with a
> package.use entry like:

> app-office/libreoffice python_single_target_python3_4
> ...
> seems to workforme too.

Hm, did you try running the resulting unoconv?  It seems that unoconv and libreoffice need to be built for the same python version. unoconv-0.7.ebuild currently in the tree lists only:

  PYTHON_COMPAT=( python{2_7,3_3} )

Note, I can _install_ both recent libreoffice (using python3_4) and unoconv (using either python2_7 or python3_3) no problem.  But unoconv will not actually work:

  $ unoconv 
  unoconv: Cannot find a suitable pyuno library and python binary combination in
  /usr/lib64/libreoffice
  ERROR: dynamic module does not define init function (initpyuno)

  unoconv: Cannot find a suitable pyuno library and python binary combination in
  /usr/lib/libreoffice
  ERROR: dynamic module does not define init function (initpyuno)

  unoconv: Cannot find a suitable office installation on your system.
  ERROR: Please locate your office installation and send your feedback to:
         http://github.com/dagwieers/unoconv/issues


unoconv appears to support Python 3.4 just fine, and if I modify the unoconv ebuild to say PYTHON_COMPAT=( python3_4 ) and re-emerge it, I get a unoconv that works:

  $ unoconv 
  unoconv: you have to provide a filename or url as argument
  Try `unoconv -h' for more information.

(And then I tested having it actually do some conversions, and they worked too.)

I will attach a patch that updates PYTHON_COMPAT=

I suspect really, some version-matching wizardry is needed so that portage will know that unoconv needs to be built with the same python version as openoffice / libreoffice.  But its main dep is virtual/ooo , which doesn't seem to use/expose python target version info, so I don't know what the right way to do that is.




Comment 5


Hank Leininger





          2016-05-05 00:17:34 UTC
        

Created attachment 433248 [details, diff]
Update unoconv ebuild to target python 3_4 for ooo compatability









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

