Title: 928410 – dev-python/freetype-py-2.4.0-r1 fails tests: collecting .. Fatal Python error: Aborted
URL: https://bugs.gentoo.org/show_bug.cgi?id=928410

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 928410
dev-python/freetype-py-2.4.0-r1 fails tests: collecting .. Fatal Python error: Aborted
Last modified: 2024-04-02 14:07:52 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 928410 
      - dev-python/freetype-py-2.4.0-r1 fails tests: collecting .. Fatal Python error: Aborted


Summary:
dev-python/freetype-py-2.4.0-r1 fails tests: collecting .. Fatal Python error...
        









Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
Normal
       normal
      


Assignee:

Python Gentoo Team








URL:







Whiteboard:




Keywords:

TESTFAILURE







Depends on:







Blocks:









 





      Reported:
    
2024-04-02 07:11 UTC by Agostino Sarubbo





      Modified:
    
2024-04-02 14:07 UTC
      (History)
    




          CC List:
        

1 
          user
          
            (show)
          



mgorny









See Also:






Package list:







Runtime testing required:

---























      Attachments
    




build.log

              (build.log,144.63 KB,
                text/plain)

            
2024-04-02 07:11 UTC,

            Agostino Sarubbo




Details





View All

Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Agostino Sarubbo






          2024-04-02 07:11:01 UTC
        

https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-python/freetype-py-2.4.0-r1 fails tests.
Discovered on: amd64 (internal ref: gcc14_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0015




Comment 1


Agostino Sarubbo






          2024-04-02 07:11:03 UTC
        

Created attachment 889240 [details]
build.log

build log and emerge --info




Comment 2


Agostino Sarubbo






          2024-04-02 07:11:04 UTC
        

Error(s) that match a know pattern in addition to what has been reported in the summary:


/var/tmp/portage/dev-python/freetype-py-2.4.0-r1/temp/environment: line 2487:    84 Aborted                 "${@}"
collecting ... Fatal Python error: Aborted




Comment 3


Michał Górny









          2024-04-02 14:07:52 UTC
        

This is a known problem with pytest+pypy3, it happens sometimes, upstream can't figure out what's causing it.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

