Title: 150729 – dev-lang/python-2.4.3-r4 fails tests
URL: https://bugs.gentoo.org/show_bug.cgi?id=150729

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 150729
dev-lang/python-2.4.3-r4 fails tests
Last modified: 2006-10-12 05:03:18 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 150729 
      - dev-lang/python-2.4.3-r4 fails tests


Summary:
dev-lang/python-2.4.3-r4 fails tests
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

New packages

  (show other bugs)



Hardware:

AMD64
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Python Gentoo Team








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2006-10-10 04:03 UTC by Boyd Stephen Smith Jr.





      Modified:
    
2006-10-12 05:03 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Boyd Stephen Smith Jr.





          2006-10-10 04:03:03 UTC
        

Emerging  with tests on gives:
[...]
240 tests OK.
1 test failed:
    test_posixpath
38 tests skipped:
    test_aepack test_al test_applesingle test_bsddb185 test_bsddb3
    test_cd test_cl test_codecmaps_cn test_codecmaps_hk
    test_codecmaps_jp test_codecmaps_kr test_codecmaps_tw test_curses
    test_dbm test_dl test_gdbm test_gl test_imageop test_imgfile
    test_linuxaudiodev test_macfs test_macostools test_nis
    test_normalization test_ossaudiodev test_pep277 test_plistlib
    test_rgbimg test_scriptpackages test_socket_ssl test_socketserver
    test_sunaudiodev test_timeout test_unicode_file test_urllib2net
    test_urllibnet test_winreg test_winsound
2 skips unexpected on linux2:
    test_dbm test_gdbm
[...]
test_exists (test.test_posixpath.PosixPathTest) ... ok
test_expanduser (test.test_posixpath.PosixPathTest) ... FAIL
test_expandvars (test.test_posixpath.PosixPathTest) ... ok
[...]
======================================================================
FAIL: test_expanduser (test.test_posixpath.PosixPathTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-lang/python-2.4.3-r4/work/Python-2.4.3/Lib/test/test_posixpath.py", line 353, in test_expanduser
    posixpath.expanduser("~/")
AssertionError: '/var/tmp/portage/dev-lang/python-2.4.3-r4/temp//' != '/var/tmp/paludis/dev-lang/python-2.4.3-r4/temp/'

----------------------------------------------------------------------
Ran 27 tests in 0.014s

FAILED (failures=1)
[...]




Comment 1


Marien Zwart (RETIRED)






          2006-10-10 07:48:34 UTC
        

emerge --info?

This makes no sense to me at all. The relevant test is:

                self.assertEqual(
                    posixpath.expanduser("~") + "/",
                    posixpath.expanduser("~/")
                )

And the only way I can see that being false is if os.environ['HOME'] or pwd.getpwuid(os.getuid()).pw_dir is changing between the two calls, neither of which makes a lot of sense. Is this reproducable? As what user are these tests running? Can you grep around for the two returned "homedirs" for this user and see if there is anything odd in your configuration related to them?




Comment 2


Boyd Stephen Smith Jr.





          2006-10-12 01:06:40 UTC
        

I'm having unable to reproduce this bug now.  I was emerging into a chroot (using the ROOT variable) and had USE set to -* for all packages in the chroot.  I'm no longer attempting that, but I've tried a couple of different way to reproduce the bug without success.




Comment 3


Marien Zwart (RETIRED)






          2006-10-12 05:03:18 UTC
        

I'm going to close this worksforme then, since I cannot think of any way this could have happened either.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

