Title: 484830 – dev-python/matplotlib-1.2.1 USE=doc - sandbox violation in /root/.cache/gegl-0.1 by gimp-2.6 file:///tmp/portage/dev-python/matplotlib-1.2.1/temp/python2.7/tmpULBZx1
URL: https://bugs.gentoo.org/show_bug.cgi?id=484830

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 484830
dev-python/matplotlib-1.2.1 USE=doc - sandbox violation in /root/.cache/gegl-0.1 by gimp-2.6 file:///tmp/portage/dev-python/matplotlib-1.2.1/temp/python2.7/tmpULBZx1
Last modified: 2013-12-14 08:12:18 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 484830 
      - dev-python/matplotlib-1.2.1 USE=doc - sandbox violation in /root/.cache/gegl-0.1 by gimp-2.6 file:///tmp/portage/dev-python/matplotlib-1.2.1/temp/python2.7/tmpULBZx1


Summary:
dev-python/matplotlib-1.2.1 USE=doc - sandbox violation in /root/.cache/gegl-...
        









Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

[OLD] Development

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
Normal
       normal
      


Assignee:

Python Gentoo Team








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2013-09-13 23:20 UTC by Luciano





      Modified:
    
2013-12-14 08:12 UTC
      (History)
    




          CC List:
        

1 
          user
          
            (show)
          



jlec









See Also:






Package list:







Runtime testing required:

---























      Attachments
    




output of emerge --info

              (emerge.info,16.29 KB,
                application/x-info)

            
2013-09-13 23:20 UTC,

            Luciano




Details





Sandbox violation log

              (sandbox-22669.log,575 bytes,
                text/x-log)

            
2013-09-13 23:20 UTC,

            Luciano




Details





full build log

              (build.log.gz,58.10 KB,
                application/x-gzip)

            
2013-09-13 23:22 UTC,

            Luciano




Details





View All

Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Luciano





          2013-09-13 23:20:13 UTC
        

Building matplotlib-1.2.1 with the doc USE flag enabled causes a sandbox violation on attempting to emerge. See attached logs.

Reproducible: Always




Comment 1


Luciano





          2013-09-13 23:20:34 UTC
        

Created attachment 358608 [details]
output of emerge --info




Comment 2


Luciano





          2013-09-13 23:20:54 UTC
        

Created attachment 358610 [details]
Sandbox violation log




Comment 3


Luciano





          2013-09-13 23:22:09 UTC
        

Created attachment 358612 [details]
full build log




Comment 4


Justin Lecher (RETIRED)






          2013-12-12 12:26:23 UTC
        

Is this still reproducible with latest matplotlib? No clue what is happening here.




Comment 5


Luciano





          2013-12-13 19:54:17 UTC
        

I can confirm this works now with matplotlib-1.3.0 and the doc flag.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

